[dut]
#pyvisa res string for hp3478
#res = 'GPIB0::23::INSTR'
res = 'TCPIP::192.168.1.12::gpib0,23::INSTR'

[calsource]
res = 'TCPIP::192.168.1.12::gpib0,20::INSTR'

[adj]
# discard a few readings then save the few next for median + stats
discard = 4
keep = 10

#default settling time for all V and low I ranges
step_dwell = 10

