[dut]
#pyvisa res string for hp3478
res = 'GPIB0::23::INSTR'

[calsource]
res = 'GPIB0::19::INSTR'

[pv]
# discard a few readings then save the few next for median + stats
discard = 4
keep = 10

#default settling time for all V and low I ranges
step_dwell = 10

#per-range settling times; optional
dly_100mA = 60
dly_1A = 240

