[dut]
#pyvisa res string for hp3478
res = 'GPIB0::23::INSTR'

[calsource]
res = 'GPIB0::19::INSTR'

[pv]
# discard a few readings then save the few next for median + stats
discard = 2
keep = 3

#default settling time for all V and low I ranges
step_dwell = 0.1

#per-range settling times; optional
dly_100mA = 1
dly_1A = 1

